markdown: rdiscount
highlighter: pygments

title: "Lorem Ipsum"
description: "Software developer from Donostia/San Sebastián"
date_format: "%B %d, %Y"
permalink: :year/:month/:day/:title:output_ext
lang: "en"

license:
  name: "Creative Commons Attribution-ShareAlike 4.0 International License"
  alias: "CC BY-SA 4.0"
  url:  http://creativecommons.org/licenses/by-sa/4.0/
  logo: "https://i.creativecommons.org/l/by-sa/4.0/80x15.png"
tools:
  jekyll:   https://github.com/mojombo/jekyll/
  skeleton: http://getskeleton.com

author:
  name:             "ASga ASoas asasdo"
  github:           rmhdev
  twitter:          rmhdev
  linkedin:         rmhdev
  email_pro:        "rober(at)rmhdev.net"
  email_personal:   "rmhdev(at)gmail.com"
  location:         "Donostia/San Sebastián"

production_url: http://rmhdev.net

repository:
  fork_me:        https://github.com/rmhdev/rmhdev.github.com
  posts_folder:   /tree/master/_posts/

analytics:
  enabled:  true
  google: 
    tracking_id:  'UA-22011276-1'
